### ISSUE TITLE
Bluetooth not working, only works over USB

### ISSUE THREAD

**Issue by ahan98** [carrefinho/forager#6]
The keyboard works with both halves plugged into my laptop over USB, but I'm unable to get connectivity over bluetooth.

Here are the exact steps I followed:

1. Fork the Forager ZMK module: https://github.com/carrefinho/forager-zmk-module
2. Push any changes to the fork and download the firmware from the workflow in the Actions tab.
3. Plug in the left half. Double tap the reset button on the controller. Flash `settings_reset-seeeduino_xiao_ble-zmk.uf2` onto the controller.
4. Double tap the reset button on the left controller again. Flash `forager_left rgbled_adapter-seeeduino_xiao_ble-zmk.uf2`. Disconnect the left half.
5. Repeat steps 3 and 4 for the right half.

After connecting the left half to the laptop over USB, then connecting the right half to the laptop over USB, I verified that every layer of the keymap is working properly. But I'm unable to get the keyboard working over bluetooth.

I also tried the following:

- Connect the left half to the laptop over USB, then connect the right half to the laptop over USB. Press the reset button on both controllers simultaneously to pair the halves to each other.
- Forget the Forager keyboard on my laptop's list of bluetooth devices. Press the key mapped to `&bt BT_CLR_ALL`.
- Press the key mapped to `&out OUT_BLE`.

The last thing I can think of is to test with different lithium ion batteries. I don't think it's a soldering issue since every key of every keymap layer works when plugged in over USB.

For the sake of reproducibility, would you mind sharing how to connect over bluetooth, similar to your build guide for the hardware? I would think it's something similar to steps 1-5, since that seems to be the standard procedure for flashing ZMK firmware (for example, the [instructions for flashing ZMK firmware for the TOTEM keyboard](https://github.com/GEIGEIGEIST/zmk-config-totem?tab=readme-ov-file#how-to-use) are pretty much the same).

Thanks!

**Comment by carrefinho** [comment]
Halves only talk to each other via Bluetooth. So if both halves are working while connected to USB, that means they're paired and connected.

Does the LED near the USB-C port light up when you click reset while on battery? If not, it's simply not getting power from the battery.

**Comment by ahan98** [comment]
I see. Yeah, when either half is not connected to the PC over USB, the light near the USB-C port of the controller doesn't light up after pressing the reset button. I'll try swapping batteries and see if that resolves the issue. Thanks for the fast reply.

**Comment by ahan98** [comment]
Ended up fixing it by reworking a cold joint on the BAT+ pad. Thanks again for the help!
